/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as faucetSol from "./Faucet.sol";
export type { faucetSol };
import type * as pairOrderSol from "./PairOrder.sol";
export type { pairOrderSol };
import type * as walletSol from "./wallet.sol";
export type { walletSol };
export type { Token0 } from "./Token0";
export type { Token1 } from "./Token1";
