/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace PairNewOrder {
  export type OrderMarketStruct = {
    isBuy: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    date: PromiseOrValue<BigNumberish>;
  };

  export type OrderMarketStructOutput = [
    number,
    BigNumber,
    BigNumber,
    BigNumber
  ] & { isBuy: number; amount: BigNumber; price: BigNumber; date: BigNumber };

  export type OrderStruct = {
    id: PromiseOrValue<BigNumberish>;
    trader: PromiseOrValue<string>;
    isBuy: PromiseOrValue<BigNumberish>;
    createdDate: PromiseOrValue<BigNumberish>;
    token: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    filled: PromiseOrValue<BigNumberish>;
    nextNodeID: PromiseOrValue<BigNumberish>;
  };

  export type OrderStructOutput = [
    BigNumber,
    string,
    number,
    BigNumber,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    id: BigNumber;
    trader: string;
    isBuy: number;
    createdDate: BigNumber;
    token: string;
    amount: BigNumber;
    price: BigNumber;
    filled: BigNumber;
    nextNodeID: BigNumber;
  };

  export type OrderHistoryStruct = {
    Type: PromiseOrValue<string>;
    isBuy: PromiseOrValue<BigNumberish>;
    amount: PromiseOrValue<BigNumberish>;
    price: PromiseOrValue<BigNumberish>;
    Trader: PromiseOrValue<string>;
    date: PromiseOrValue<BigNumberish>;
  };

  export type OrderHistoryStructOutput = [
    string,
    number,
    BigNumber,
    BigNumber,
    string,
    BigNumber
  ] & {
    Type: string;
    isBuy: number;
    amount: BigNumber;
    price: BigNumber;
    Trader: string;
    date: BigNumber;
  };
}

export interface PairNewOrderInterface extends utils.Interface {
  functions: {
    "_findIndex(uint256,uint8)": FunctionFragment;
    "_findPrevOrder(uint8,uint256)": FunctionFragment;
    "balancesSpot(address,address)": FunctionFragment;
    "balancesTrade(address,address)": FunctionFragment;
    "createLimitOrder(uint8,uint256,uint256,uint256)": FunctionFragment;
    "createMarketOrder(uint8,uint256,uint256)": FunctionFragment;
    "deposit(uint256,address)": FunctionFragment;
    "getMarketOrder()": FunctionFragment;
    "getOrderBook(uint8)": FunctionFragment;
    "getOrderHisotyByAddress(address)": FunctionFragment;
    "price()": FunctionFragment;
    "removeOrder(uint8,uint256,uint256)": FunctionFragment;
    "updateOrder(uint8,uint256,uint256,uint256,uint256,uint256)": FunctionFragment;
    "withdraw(uint256,address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "_findIndex"
      | "_findPrevOrder"
      | "balancesSpot"
      | "balancesTrade"
      | "createLimitOrder"
      | "createMarketOrder"
      | "deposit"
      | "getMarketOrder"
      | "getOrderBook"
      | "getOrderHisotyByAddress"
      | "price"
      | "removeOrder"
      | "updateOrder"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "_findIndex",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "_findPrevOrder",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "balancesSpot",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "balancesTrade",
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "createLimitOrder",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createMarketOrder",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getMarketOrder",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderBook",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderHisotyByAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "price", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeOrder",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateOrder",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(functionFragment: "_findIndex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "_findPrevOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balancesSpot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balancesTrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLimitOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createMarketOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getMarketOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderBook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderHisotyByAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "price", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateOrder",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "CreateLimitOrder(uint8,uint256,uint256,address)": EventFragment;
    "MarketOrder(uint8,uint256,uint256)": EventFragment;
    "RemoveOrder(uint8,uint256,uint256,address)": EventFragment;
    "SumMarketOrder(uint8,uint256,address)": EventFragment;
    "UpdateOrder(uint8,uint256,uint256,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CreateLimitOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MarketOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RemoveOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SumMarketOrder"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "UpdateOrder"): EventFragment;
}

export interface CreateLimitOrderEventObject {
  _isBuy: number;
  _amount: BigNumber;
  _price: BigNumber;
  trader: string;
}
export type CreateLimitOrderEvent = TypedEvent<
  [number, BigNumber, BigNumber, string],
  CreateLimitOrderEventObject
>;

export type CreateLimitOrderEventFilter =
  TypedEventFilter<CreateLimitOrderEvent>;

export interface MarketOrderEventObject {
  _isBuy: number;
  _amount: BigNumber;
  _price: BigNumber;
}
export type MarketOrderEvent = TypedEvent<
  [number, BigNumber, BigNumber],
  MarketOrderEventObject
>;

export type MarketOrderEventFilter = TypedEventFilter<MarketOrderEvent>;

export interface RemoveOrderEventObject {
  _isBuy: number;
  _amount: BigNumber;
  _price: BigNumber;
  trader: string;
}
export type RemoveOrderEvent = TypedEvent<
  [number, BigNumber, BigNumber, string],
  RemoveOrderEventObject
>;

export type RemoveOrderEventFilter = TypedEventFilter<RemoveOrderEvent>;

export interface SumMarketOrderEventObject {
  _isBuy: number;
  _amount: BigNumber;
  trader: string;
}
export type SumMarketOrderEvent = TypedEvent<
  [number, BigNumber, string],
  SumMarketOrderEventObject
>;

export type SumMarketOrderEventFilter = TypedEventFilter<SumMarketOrderEvent>;

export interface UpdateOrderEventObject {
  _isBuy: number;
  newPriceOrder: BigNumber;
  newAmount: BigNumber;
  trader: string;
}
export type UpdateOrderEvent = TypedEvent<
  [number, BigNumber, BigNumber, string],
  UpdateOrderEventObject
>;

export type UpdateOrderEventFilter = TypedEventFilter<UpdateOrderEvent>;

export interface PairNewOrder extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: PairNewOrderInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    _findIndex(
      _price: PromiseOrValue<BigNumberish>,
      _isBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    _findPrevOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balancesSpot(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balancesTrade(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    createLimitOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      prevNodeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    createMarketOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getMarketOrder(
      overrides?: CallOverrides
    ): Promise<[PairNewOrder.OrderMarketStructOutput[]]>;

    getOrderBook(
      _isBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[PairNewOrder.OrderStructOutput[]]>;

    getOrderHisotyByAddress(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[PairNewOrder.OrderHistoryStructOutput[]]>;

    price(overrides?: CallOverrides): Promise<[BigNumber]>;

    removeOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      prevIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      newPriceOrder: PromiseOrValue<BigNumberish>,
      newAmount: PromiseOrValue<BigNumberish>,
      prevIndexAdd: PromiseOrValue<BigNumberish>,
      prevIndexRemove: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  _findIndex(
    _price: PromiseOrValue<BigNumberish>,
    _isBuy: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  _findPrevOrder(
    _isBuy: PromiseOrValue<BigNumberish>,
    index: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balancesSpot(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balancesTrade(
    arg0: PromiseOrValue<string>,
    arg1: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  createLimitOrder(
    _isBuy: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    prevNodeID: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  createMarketOrder(
    _isBuy: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    _price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  deposit(
    amount: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getMarketOrder(
    overrides?: CallOverrides
  ): Promise<PairNewOrder.OrderMarketStructOutput[]>;

  getOrderBook(
    _isBuy: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<PairNewOrder.OrderStructOutput[]>;

  getOrderHisotyByAddress(
    _address: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<PairNewOrder.OrderHistoryStructOutput[]>;

  price(overrides?: CallOverrides): Promise<BigNumber>;

  removeOrder(
    _isBuy: PromiseOrValue<BigNumberish>,
    index: PromiseOrValue<BigNumberish>,
    prevIndex: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateOrder(
    _isBuy: PromiseOrValue<BigNumberish>,
    index: PromiseOrValue<BigNumberish>,
    newPriceOrder: PromiseOrValue<BigNumberish>,
    newAmount: PromiseOrValue<BigNumberish>,
    prevIndexAdd: PromiseOrValue<BigNumberish>,
    prevIndexRemove: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    amount: PromiseOrValue<BigNumberish>,
    token: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    _findIndex(
      _price: PromiseOrValue<BigNumberish>,
      _isBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _findPrevOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balancesSpot(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balancesTrade(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createLimitOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      prevNodeID: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    createMarketOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    getMarketOrder(
      overrides?: CallOverrides
    ): Promise<PairNewOrder.OrderMarketStructOutput[]>;

    getOrderBook(
      _isBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PairNewOrder.OrderStructOutput[]>;

    getOrderHisotyByAddress(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PairNewOrder.OrderHistoryStructOutput[]>;

    price(overrides?: CallOverrides): Promise<BigNumber>;

    removeOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      prevIndex: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      newPriceOrder: PromiseOrValue<BigNumberish>,
      newAmount: PromiseOrValue<BigNumberish>,
      prevIndexAdd: PromiseOrValue<BigNumberish>,
      prevIndexRemove: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CreateLimitOrder(uint8,uint256,uint256,address)"(
      _isBuy?: null,
      _amount?: null,
      _price?: null,
      trader?: PromiseOrValue<string> | null
    ): CreateLimitOrderEventFilter;
    CreateLimitOrder(
      _isBuy?: null,
      _amount?: null,
      _price?: null,
      trader?: PromiseOrValue<string> | null
    ): CreateLimitOrderEventFilter;

    "MarketOrder(uint8,uint256,uint256)"(
      _isBuy?: null,
      _amount?: null,
      _price?: null
    ): MarketOrderEventFilter;
    MarketOrder(
      _isBuy?: null,
      _amount?: null,
      _price?: null
    ): MarketOrderEventFilter;

    "RemoveOrder(uint8,uint256,uint256,address)"(
      _isBuy?: null,
      _amount?: null,
      _price?: null,
      trader?: PromiseOrValue<string> | null
    ): RemoveOrderEventFilter;
    RemoveOrder(
      _isBuy?: null,
      _amount?: null,
      _price?: null,
      trader?: PromiseOrValue<string> | null
    ): RemoveOrderEventFilter;

    "SumMarketOrder(uint8,uint256,address)"(
      _isBuy?: null,
      _amount?: null,
      trader?: PromiseOrValue<string> | null
    ): SumMarketOrderEventFilter;
    SumMarketOrder(
      _isBuy?: null,
      _amount?: null,
      trader?: PromiseOrValue<string> | null
    ): SumMarketOrderEventFilter;

    "UpdateOrder(uint8,uint256,uint256,address)"(
      _isBuy?: null,
      newPriceOrder?: null,
      newAmount?: null,
      trader?: PromiseOrValue<string> | null
    ): UpdateOrderEventFilter;
    UpdateOrder(
      _isBuy?: null,
      newPriceOrder?: null,
      newAmount?: null,
      trader?: PromiseOrValue<string> | null
    ): UpdateOrderEventFilter;
  };

  estimateGas: {
    _findIndex(
      _price: PromiseOrValue<BigNumberish>,
      _isBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    _findPrevOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balancesSpot(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balancesTrade(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    createLimitOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      prevNodeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    createMarketOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getMarketOrder(overrides?: CallOverrides): Promise<BigNumber>;

    getOrderBook(
      _isBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getOrderHisotyByAddress(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    price(overrides?: CallOverrides): Promise<BigNumber>;

    removeOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      prevIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      newPriceOrder: PromiseOrValue<BigNumberish>,
      newAmount: PromiseOrValue<BigNumberish>,
      prevIndexAdd: PromiseOrValue<BigNumberish>,
      prevIndexRemove: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdraw(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    _findIndex(
      _price: PromiseOrValue<BigNumberish>,
      _isBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    _findPrevOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balancesSpot(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balancesTrade(
      arg0: PromiseOrValue<string>,
      arg1: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    createLimitOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      prevNodeID: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    createMarketOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    deposit(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getMarketOrder(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getOrderBook(
      _isBuy: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getOrderHisotyByAddress(
      _address: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    price(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      prevIndex: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateOrder(
      _isBuy: PromiseOrValue<BigNumberish>,
      index: PromiseOrValue<BigNumberish>,
      newPriceOrder: PromiseOrValue<BigNumberish>,
      newAmount: PromiseOrValue<BigNumberish>,
      prevIndexAdd: PromiseOrValue<BigNumberish>,
      prevIndexRemove: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      amount: PromiseOrValue<BigNumberish>,
      token: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
